### ISSUE TITLE
Need to change module name to match package definition name

### ISSUE THREAD

**Issue by philipbarrett** [cc7768/CHull2d.jl#2]
Chase - Changing the name of src/CHull2D.jl to src/CHull2d.jl is a good move, but you also need to change the module definition line to reflect this.  LIne 16 of this file should now read `module CHull2d`, otherwise users get an error.  Thanks!

**Comment by cc7768** [comment]
Doh -- Thanks for this. I have it changed locally on one of my machines (who knows which one), but I should have this changed in repo as well.

**Comment by cc7768** [comment]
Let me know if that doesn't fix it.
